export const ART_CATEGORIES = [
  "Animals",
  "People",
  "Vehicles",
  "Architecture",
  "Nature & Plants",
  "Sci-Fi",
  "Fantasy",
  "Games & Toys",
  "Cultural Heritage",
  "Science & Education",
  "Music & Instruments",
  "Fashion & Accessories",
  "Food & Drink",
  "Sports & Fitness",
  "Health & Wellness",
  "Technology & Gadgets",
  "History & Archaeology",
  "Travel & Exploration",
  "Space & Astronomy",
  "Cartoons & Comics",
  "Abstract & Surreal",
  "Landscapes & Scenery",
  "Machinery & Industrial",
  "Religion & Spirituality",
  "Mythology & Folklore",
  "Watercraft",
  "Military & Defense",
  "Politics & Government",
  "Economics & Finance",
  "Business & Entrepreneurship",
  "Education & Learning",
  "Entertainment & Media",
  "Social Issues",
  "Environment & Conservation",
  "Medicine & Healthcare",
  "Art & Creativity",
  "Human Rights & Justice",
  "Philosophy & Ethics",
  "Literature & Writing",
  "Film & Theater",
  "Photography",
  "Digital Art",
  "Painting",
  "Sculpture",
  "Drawing",
  "Printmaking",
  "Mixed Media",
  "Performance Art",
];
