export enum QueryKey {
  ARTS = "ARTS",
  ART_DETAILS = "ART_DETAILS",
  ART_HOME = "ART_HOME",
  ART = "ART",
  RECOMMENDED_ARTS = "RECOMMENDED_ARTS",
  PROFILE = "PROFILE",
  USER = "USER",
}
